insert into "location" values (gen_random_uuid(), 'RS', 'Porto Alegre'),
   (gen_random_uuid(), 'RS', 'Aceguá'),
   (gen_random_uuid(), 'RS', 'Água Santa'),
   (gen_random_uuid(), 'RS', 'Agudo'),
   (gen_random_uuid(), 'RS', 'Ajuricaba'),
   (gen_random_uuid(), 'RS', 'Alecrim'),
   (gen_random_uuid(), 'RS', 'Alegrete'),
   (gen_random_uuid(), 'RS', 'Alegria'),
   (gen_random_uuid(), 'RS', 'Almirante Tamandaré do Sul'),
   (gen_random_uuid(), 'RS', 'Alpestre'),
   (gen_random_uuid(), 'RS', 'Alto Alegre'),
   (gen_random_uuid(), 'RS', 'Alto Feliz'),
   (gen_random_uuid(), 'RS', 'Alvorada'),
   (gen_random_uuid(), 'RS', 'Amaral Ferrador'),
   (gen_random_uuid(), 'RS', 'Ametista do Sul'),
   (gen_random_uuid(), 'RS', 'André da Rocha'),
   (gen_random_uuid(), 'RS', 'Anta Gorda'),
   (gen_random_uuid(), 'RS', 'Antônio Prado'),
   (gen_random_uuid(), 'RS', 'Arambaré'),
   (gen_random_uuid(), 'RS', 'Araricá'),
   (gen_random_uuid(), 'RS', 'Aratiba'),
   (gen_random_uuid(), 'RS', 'Arroio do Meio'),
   (gen_random_uuid(), 'RS', 'Arroio do Padre'),
   (gen_random_uuid(), 'RS', 'Arroio do Sal'),
   (gen_random_uuid(), 'RS', 'Arroio do Tigre'),
   (gen_random_uuid(), 'RS', 'Arroio dos Ratos'),
   (gen_random_uuid(), 'RS', 'Arroio Grande'),
   (gen_random_uuid(), 'RS', 'Arvorezinha'),
   (gen_random_uuid(), 'RS', 'Augusto Pestana'),
   (gen_random_uuid(), 'RS', 'Áurea'),
   (gen_random_uuid(), 'RS', 'Bagé'),
   (gen_random_uuid(), 'RS', 'Balneário Pinhal'),
   (gen_random_uuid(), 'RS', 'Barão'),
   (gen_random_uuid(), 'RS', 'Barão de Cotegipe'),
   (gen_random_uuid(), 'RS', 'Barão do Triunfo'),
   (gen_random_uuid(), 'RS', 'Barra do Guarita'),
   (gen_random_uuid(), 'RS', 'Barra do Quaraí'),
   (gen_random_uuid(), 'RS', 'Barra do Ribeiro'),
   (gen_random_uuid(), 'RS', 'Barra do Rio Azul'),
   (gen_random_uuid(), 'RS', 'Barra Funda'),
   (gen_random_uuid(), 'RS', 'Barracão'),
   (gen_random_uuid(), 'RS', 'Barros Cassal'),
   (gen_random_uuid(), 'RS', 'Benjamin Constan do Sul'),
   (gen_random_uuid(), 'RS', 'Bento Gonçalves'),
   (gen_random_uuid(), 'RS', 'Boa Vista das Missões'),
   (gen_random_uuid(), 'RS', 'Boa Vista do Buricá'),
   (gen_random_uuid(), 'RS', 'Boa Vista do Cadeado'),
   (gen_random_uuid(), 'RS', 'Boa Vista do Incra'),
   (gen_random_uuid(), 'RS', 'Boa Vista do Sul'),
   (gen_random_uuid(), 'RS', 'Bom Jesus'),
   (gen_random_uuid(), 'RS', 'Bom Princípio'),
   (gen_random_uuid(), 'RS', 'Bom Progresso'),
   (gen_random_uuid(), 'RS', 'Bom Retiro do Sul'),
   (gen_random_uuid(), 'RS', 'Boqueirão do Leão'),
   (gen_random_uuid(), 'RS', 'Bossoroca'),
   (gen_random_uuid(), 'RS', 'Bozano'),
   (gen_random_uuid(), 'RS', 'Braga'),
   (gen_random_uuid(), 'RS', 'Brochier'),
   (gen_random_uuid(), 'RS', 'Butiá'),
   (gen_random_uuid(), 'RS', 'Caçapava do Sul'),
   (gen_random_uuid(), 'RS', 'Cacequi'),
   (gen_random_uuid(), 'RS', 'Cachoeira do Sul'),
   (gen_random_uuid(), 'RS', 'Cachoeirinha'),
   (gen_random_uuid(), 'RS', 'Cacique Doble'),
   (gen_random_uuid(), 'RS', 'Caibaté'),
   (gen_random_uuid(), 'RS', 'Caiçara'),
   (gen_random_uuid(), 'RS', 'Camaquã'),
   (gen_random_uuid(), 'RS', 'Camargo'),
   (gen_random_uuid(), 'RS', 'Cambará do Sul'),
   (gen_random_uuid(), 'RS', 'Campestre da Serra'),
   (gen_random_uuid(), 'RS', 'Campina das Missões'),
   (gen_random_uuid(), 'RS', 'Campinas do Sul'),
   (gen_random_uuid(), 'RS', 'Campo Bom'),
   (gen_random_uuid(), 'RS', 'Campo Novo'),
   (gen_random_uuid(), 'RS', 'Campos Borges'),
   (gen_random_uuid(), 'RS', 'Candelária'),
   (gen_random_uuid(), 'RS', 'Cândido Godói'),
   (gen_random_uuid(), 'RS', 'Candiota'),
   (gen_random_uuid(), 'RS', 'Canela'),
   (gen_random_uuid(), 'RS', 'Canguçu'),
   (gen_random_uuid(), 'RS', 'Canoas'),
   (gen_random_uuid(), 'RS', 'Canudos do Vale'),
   (gen_random_uuid(), 'RS', 'Capão Bonito do Sul'),
   (gen_random_uuid(), 'RS', 'Capão da Canoa'),
   (gen_random_uuid(), 'RS', 'Capão do Cipó'),
   (gen_random_uuid(), 'RS', 'Capão do Leão'),
   (gen_random_uuid(), 'RS', 'Capela de Santana'),
   (gen_random_uuid(), 'RS', 'Capitão'),
   (gen_random_uuid(), 'RS', 'Capivari do Sul'),
   (gen_random_uuid(), 'RS', 'Caraá'),
   (gen_random_uuid(), 'RS', 'Carazinho'),
   (gen_random_uuid(), 'RS', 'Carlos Barbosa'),
   (gen_random_uuid(), 'RS', 'Carlos Gomes'),
   (gen_random_uuid(), 'RS', 'Casca'),
   (gen_random_uuid(), 'RS', 'Caseiros'),
   (gen_random_uuid(), 'RS', 'Catuípe'),
   (gen_random_uuid(), 'RS', 'Caxias do Sul'),
   (gen_random_uuid(), 'RS', 'Centenário'),
   (gen_random_uuid(), 'RS', 'Cerrito'),
   (gen_random_uuid(), 'RS', 'Cerro Branco'),
   (gen_random_uuid(), 'RS', 'Cerro Grande'),
   (gen_random_uuid(), 'RS', 'Cerro Grande do Sul'),
   (gen_random_uuid(), 'RS', 'Cerro Largo'),
   (gen_random_uuid(), 'RS', 'Chapada'),
   (gen_random_uuid(), 'RS', 'Charqueadas'),
   (gen_random_uuid(), 'RS', 'Charrua'),
   (gen_random_uuid(), 'RS', 'Chiapeta'),
   (gen_random_uuid(), 'RS', 'Chuí'),
   (gen_random_uuid(), 'RS', 'Chuvisca'),
   (gen_random_uuid(), 'RS', 'Cidreira'),
   (gen_random_uuid(), 'RS', 'Ciríaco'),
   (gen_random_uuid(), 'RS', 'Colinas'),
   (gen_random_uuid(), 'RS', 'Colorado'),
   (gen_random_uuid(), 'RS', 'Condor'),
   (gen_random_uuid(), 'RS', 'Constantina'),
   (gen_random_uuid(), 'RS', 'Coqueiro Baixo'),
   (gen_random_uuid(), 'RS', 'Coqueiros do Sul'),
   (gen_random_uuid(), 'RS', 'Coronel Barros'),
   (gen_random_uuid(), 'RS', 'Coronel Bicaco'),
   (gen_random_uuid(), 'RS', 'Coronel Pilar'),
   (gen_random_uuid(), 'RS', 'Cotiporã'),
   (gen_random_uuid(), 'RS', 'Coxilha'),
   (gen_random_uuid(), 'RS', 'Crissiumal'),
   (gen_random_uuid(), 'RS', 'Cristal'),
   (gen_random_uuid(), 'RS', 'Cristal do Sul'),
   (gen_random_uuid(), 'RS', 'Cruz Alta'),
   (gen_random_uuid(), 'RS', 'Cruzaltense'),
   (gen_random_uuid(), 'RS', 'Cruzeiro do Sul'),
   (gen_random_uuid(), 'RS', 'David Canabarro'),
   (gen_random_uuid(), 'RS', 'Derrubadas'),
   (gen_random_uuid(), 'RS', 'Dezesseis de Novembro'),
   (gen_random_uuid(), 'RS', 'Dilermando de Aguiar'),
   (gen_random_uuid(), 'RS', 'Dois Irmãos'),
   (gen_random_uuid(), 'RS', 'Dois Irmãos das Missões'),
   (gen_random_uuid(), 'RS', 'Dois Lajeados'),
   (gen_random_uuid(), 'RS', 'Dom Feliciano'),
   (gen_random_uuid(), 'RS', 'Dom Pedrito'),
   (gen_random_uuid(), 'RS', 'Dom Pedro de Alcântara'),
   (gen_random_uuid(), 'RS', 'Dona Francisca'),
   (gen_random_uuid(), 'RS', 'Doutor Maurício Cardoso'),
   (gen_random_uuid(), 'RS', 'Doutor Ricardo'),
   (gen_random_uuid(), 'RS', 'Eldorado do Sul'),
   (gen_random_uuid(), 'RS', 'Encantado'),
   (gen_random_uuid(), 'RS', 'Encruzilhada do Sul'),
   (gen_random_uuid(), 'RS', 'Engenho Velho'),
   (gen_random_uuid(), 'RS', 'Entre Rios do Sul'),
   (gen_random_uuid(), 'RS', 'Entre-Ijuís'),
   (gen_random_uuid(), 'RS', 'Erebango'),
   (gen_random_uuid(), 'RS', 'Erechim'),
   (gen_random_uuid(), 'RS', 'Ernestina'),
   (gen_random_uuid(), 'RS', 'Erval Grande'),
   (gen_random_uuid(), 'RS', 'Erval Seco'),
   (gen_random_uuid(), 'RS', 'Esmeralda'),
   (gen_random_uuid(), 'RS', 'Esperança do Sul'),
   (gen_random_uuid(), 'RS', 'Espumoso'),
   (gen_random_uuid(), 'RS', 'Estação'),
   (gen_random_uuid(), 'RS', 'Estância Velha'),
   (gen_random_uuid(), 'RS', 'Esteio'),
   (gen_random_uuid(), 'RS', 'Estrela'),
   (gen_random_uuid(), 'RS', 'Estrela Velha'),
   (gen_random_uuid(), 'RS', 'Eugênio de Castro'),
   (gen_random_uuid(), 'RS', 'Fagundes Varela'),
   (gen_random_uuid(), 'RS', 'Farroupilha'),
   (gen_random_uuid(), 'RS', 'Faxinal do Soturno'),
   (gen_random_uuid(), 'RS', 'Faxinalzinho'),
   (gen_random_uuid(), 'RS', 'Fazenda Vilanova'),
   (gen_random_uuid(), 'RS', 'Feliz'),
   (gen_random_uuid(), 'RS', 'Flores da Cunha'),
   (gen_random_uuid(), 'RS', 'Floriano Peixoto'),
   (gen_random_uuid(), 'RS', 'Fontoura Xavier'),
   (gen_random_uuid(), 'RS', 'Formigueiro'),
   (gen_random_uuid(), 'RS', 'Forquetinha'),
   (gen_random_uuid(), 'RS', 'Fortaleza dos Valos'),
   (gen_random_uuid(), 'RS', 'Frederico Westphalen'),
   (gen_random_uuid(), 'RS', 'Garibaldi'),
   (gen_random_uuid(), 'RS', 'Garruchos'),
   (gen_random_uuid(), 'RS', 'Gaurama'),
   (gen_random_uuid(), 'RS', 'General Câmara'),
   (gen_random_uuid(), 'RS', 'Gentil'),
   (gen_random_uuid(), 'RS', 'Getúlio Vargas'),
   (gen_random_uuid(), 'RS', 'Giruá'),
   (gen_random_uuid(), 'RS', 'Glorinha'),
   (gen_random_uuid(), 'RS', 'Gramado'),
   (gen_random_uuid(), 'RS', 'Gramado dos Loureiros'),
   (gen_random_uuid(), 'RS', 'Gramado Xavier'),
   (gen_random_uuid(), 'RS', 'Gravataí'),
   (gen_random_uuid(), 'RS', 'Guabiju'),
   (gen_random_uuid(), 'RS', 'Guaíba'),
   (gen_random_uuid(), 'RS', 'Guaporé'),
   (gen_random_uuid(), 'RS', 'Guarani das Missões'),
   (gen_random_uuid(), 'RS', 'Harmonia'),
   (gen_random_uuid(), 'RS', 'Herval'),
   (gen_random_uuid(), 'RS', 'Herveiras'),
   (gen_random_uuid(), 'RS', 'Horizontina'),
   (gen_random_uuid(), 'RS', 'Hulha Negra'),
   (gen_random_uuid(), 'RS', 'Humaitá'),
   (gen_random_uuid(), 'RS', 'Ibarama'),
   (gen_random_uuid(), 'RS', 'Ibiaçá'),
   (gen_random_uuid(), 'RS', 'Ibiraiaras'),
   (gen_random_uuid(), 'RS', 'Ibirapuitã'),
   (gen_random_uuid(), 'RS', 'Ibirubá'),
   (gen_random_uuid(), 'RS', 'Igrejinha'),
   (gen_random_uuid(), 'RS', 'Ijuí'),
   (gen_random_uuid(), 'RS', 'Ilópolis'),
   (gen_random_uuid(), 'RS', 'Imbé'),
   (gen_random_uuid(), 'RS', 'Imigrante'),
   (gen_random_uuid(), 'RS', 'Independência'),
   (gen_random_uuid(), 'RS', 'Inhacorá'),
   (gen_random_uuid(), 'RS', 'Ipê'),
   (gen_random_uuid(), 'RS', 'Ipiranga do Sul'),
   (gen_random_uuid(), 'RS', 'Iraí'),
   (gen_random_uuid(), 'RS', 'Itaara'),
   (gen_random_uuid(), 'RS', 'Itacurubi'),
   (gen_random_uuid(), 'RS', 'Itapuca'),
   (gen_random_uuid(), 'RS', 'Itaqui'),
   (gen_random_uuid(), 'RS', 'Itati'),
   (gen_random_uuid(), 'RS', 'Itatiba do Sul'),
   (gen_random_uuid(), 'RS', 'Ivorá'),
   (gen_random_uuid(), 'RS', 'Ivoti'),
   (gen_random_uuid(), 'RS', 'Jaboticaba'),
   (gen_random_uuid(), 'RS', 'Jacuizinho'),
   (gen_random_uuid(), 'RS', 'Jacutinga'),
   (gen_random_uuid(), 'RS', 'Jaguarão'),
   (gen_random_uuid(), 'RS', 'Jaguari'),
   (gen_random_uuid(), 'RS', 'Jaquirana'),
   (gen_random_uuid(), 'RS', 'Jari'),
   (gen_random_uuid(), 'RS', 'Jóia'),
   (gen_random_uuid(), 'RS', 'Júlio de Castilhos'),
   (gen_random_uuid(), 'RS', 'Lagoa Bonita do Sul'),
   (gen_random_uuid(), 'RS', 'Lagoa dos Três Cantos'),
   (gen_random_uuid(), 'RS', 'Lagoa Vermelha'),
   (gen_random_uuid(), 'RS', 'Lagoão'),
   (gen_random_uuid(), 'RS', 'Lajeado'),
   (gen_random_uuid(), 'RS', 'Lajeado do Bugre'),
   (gen_random_uuid(), 'RS', 'Lavras do Sul'),
   (gen_random_uuid(), 'RS', 'Liberato Salzano'),
   (gen_random_uuid(), 'RS', 'Lindolfo Collor'),
   (gen_random_uuid(), 'RS', 'Linha Nova'),
   (gen_random_uuid(), 'RS', 'Maçambara'),
   (gen_random_uuid(), 'RS', 'Machadinho'),
   (gen_random_uuid(), 'RS', 'Mampituba'),
   (gen_random_uuid(), 'RS', 'Manoel Viana'),
   (gen_random_uuid(), 'RS', 'Maquiné'),
   (gen_random_uuid(), 'RS', 'Maratá'),
   (gen_random_uuid(), 'RS', 'Marau'),
   (gen_random_uuid(), 'RS', 'Marcelino Ramos'),
   (gen_random_uuid(), 'RS', 'Mariana Pimentel'),
   (gen_random_uuid(), 'RS', 'Mariano Moro'),
   (gen_random_uuid(), 'RS', 'Marques de Souza'),
   (gen_random_uuid(), 'RS', 'Mata'),
   (gen_random_uuid(), 'RS', 'Mato Castelhano'),
   (gen_random_uuid(), 'RS', 'Mato Leitão'),
   (gen_random_uuid(), 'RS', 'Mato Queimado'),
   (gen_random_uuid(), 'RS', 'Maximiliano de Almeida'),
   (gen_random_uuid(), 'RS', 'Minas do Leão'),
   (gen_random_uuid(), 'RS', 'Miraguaí'),
   (gen_random_uuid(), 'RS', 'Montauri'),
   (gen_random_uuid(), 'RS', 'Monte Alegre dos Campos'),
   (gen_random_uuid(), 'RS', 'Monte Belo do Sul'),
   (gen_random_uuid(), 'RS', 'Montenegro'),
   (gen_random_uuid(), 'RS', 'Mormaço'),
   (gen_random_uuid(), 'RS', 'Morrinhos do Sul'),
   (gen_random_uuid(), 'RS', 'Morro Redondo'),
   (gen_random_uuid(), 'RS', 'Morro Reuter'),
   (gen_random_uuid(), 'RS', 'Mostardas'),
   (gen_random_uuid(), 'RS', 'Muçum'),
   (gen_random_uuid(), 'RS', 'Muitos Capões'),
   (gen_random_uuid(), 'RS', 'Muliterno'),
   (gen_random_uuid(), 'RS', 'Não-Me-Toque'),
   (gen_random_uuid(), 'RS', 'Nicolau Vergueiro'),
   (gen_random_uuid(), 'RS', 'Nonoai'),
   (gen_random_uuid(), 'RS', 'Nova Alvorada'),
   (gen_random_uuid(), 'RS', 'Nova Araçá'),
   (gen_random_uuid(), 'RS', 'Nova Bassano'),
   (gen_random_uuid(), 'RS', 'Nova Boa Vista'),
   (gen_random_uuid(), 'RS', 'Nova Bréscia'),
   (gen_random_uuid(), 'RS', 'Nova Candelária'),
   (gen_random_uuid(), 'RS', 'Nova Esperança do Sul'),
   (gen_random_uuid(), 'RS', 'Nova Hartz'),
   (gen_random_uuid(), 'RS', 'Nova Pádua'),
   (gen_random_uuid(), 'RS', 'Nova Palma'),
   (gen_random_uuid(), 'RS', 'Nova Petrópolis'),
   (gen_random_uuid(), 'RS', 'Nova Prata'),
   (gen_random_uuid(), 'RS', 'Nova Ramada'),
   (gen_random_uuid(), 'RS', 'Nova Roma do Sul'),
   (gen_random_uuid(), 'RS', 'Nova Santa Rita'),
   (gen_random_uuid(), 'RS', 'Novo Barreiro'),
   (gen_random_uuid(), 'RS', 'Novo Cabrais'),
   (gen_random_uuid(), 'RS', 'Novo Hamburgo'),
   (gen_random_uuid(), 'RS', 'Novo Machado'),
   (gen_random_uuid(), 'RS', 'Novo Tiradentes'),
   (gen_random_uuid(), 'RS', 'Novo Xingu'),
   (gen_random_uuid(), 'RS', 'Osório'),
   (gen_random_uuid(), 'RS', 'Paim Filho'),
   (gen_random_uuid(), 'RS', 'Palmares do Sul'),
   (gen_random_uuid(), 'RS', 'Palmeira das Missões'),
   (gen_random_uuid(), 'RS', 'Palmitinho'),
   (gen_random_uuid(), 'RS', 'Panambi'),
   (gen_random_uuid(), 'RS', 'Pântano Grande'),
   (gen_random_uuid(), 'RS', 'Paraí'),
   (gen_random_uuid(), 'RS', 'Paraíso do Sul'),
   (gen_random_uuid(), 'RS', 'Pareci Novo'),
   (gen_random_uuid(), 'RS', 'Parobé'),
   (gen_random_uuid(), 'RS', 'Passa Sete'),
   (gen_random_uuid(), 'RS', 'Passo do Sobrado'),
   (gen_random_uuid(), 'RS', 'Passo Fundo'),
   (gen_random_uuid(), 'RS', 'Paulo Bento'),
   (gen_random_uuid(), 'RS', 'Paverama'),
   (gen_random_uuid(), 'RS', 'Pedras Altas'),
   (gen_random_uuid(), 'RS', 'Pedro Osório'),
   (gen_random_uuid(), 'RS', 'Pejuçara'),
   (gen_random_uuid(), 'RS', 'Pelotas'),
   (gen_random_uuid(), 'RS', 'Picada Café'),
   (gen_random_uuid(), 'RS', 'Pinhal'),
   (gen_random_uuid(), 'RS', 'Pinhal da Serra'),
   (gen_random_uuid(), 'RS', 'Pinhal Grande'),
   (gen_random_uuid(), 'RS', 'Pinheirinho do Vale'),
   (gen_random_uuid(), 'RS', 'Pinheiro Machado'),
   (gen_random_uuid(), 'RS', 'Pirapó'),
   (gen_random_uuid(), 'RS', 'Piratini'),
   (gen_random_uuid(), 'RS', 'Planalto'),
   (gen_random_uuid(), 'RS', 'Poço das Antas'),
   (gen_random_uuid(), 'RS', 'Pontão'),
   (gen_random_uuid(), 'RS', 'Ponte Preta'),
   (gen_random_uuid(), 'RS', 'Portão'),
   (gen_random_uuid(), 'RS', 'Porto Lucena'),
   (gen_random_uuid(), 'RS', 'Porto Mauá'),
   (gen_random_uuid(), 'RS', 'Porto Vera Cruz'),
   (gen_random_uuid(), 'RS', 'Porto Xavier'),
   (gen_random_uuid(), 'RS', 'Pouso Novo'),
   (gen_random_uuid(), 'RS', 'Presidente Lucena'),
   (gen_random_uuid(), 'RS', 'Progresso'),
   (gen_random_uuid(), 'RS', 'Protásio Alves'),
   (gen_random_uuid(), 'RS', 'Putinga'),
   (gen_random_uuid(), 'RS', 'Quaraí'),
   (gen_random_uuid(), 'RS', 'Quatro Irmãos'),
   (gen_random_uuid(), 'RS', 'Quevedos'),
   (gen_random_uuid(), 'RS', 'Quinze de Novembro'),
   (gen_random_uuid(), 'RS', 'Redentora'),
   (gen_random_uuid(), 'RS', 'Relvado'),
   (gen_random_uuid(), 'RS', 'Restinga Seca'),
   (gen_random_uuid(), 'RS', 'Rio dos Índios'),
   (gen_random_uuid(), 'RS', 'Rio Grande'),
   (gen_random_uuid(), 'RS', 'Rio Pardo'),
   (gen_random_uuid(), 'RS', 'Riozinho'),
   (gen_random_uuid(), 'RS', 'Roca Sales'),
   (gen_random_uuid(), 'RS', 'Rodeio Bonito'),
   (gen_random_uuid(), 'RS', 'Rolador'),
   (gen_random_uuid(), 'RS', 'Rolante'),
   (gen_random_uuid(), 'RS', 'Ronda Alta'),
   (gen_random_uuid(), 'RS', 'Rondinha'),
   (gen_random_uuid(), 'RS', 'Roque Gonzales'),
   (gen_random_uuid(), 'RS', 'Rosário do Sul'),
   (gen_random_uuid(), 'RS', 'Sagrada Família'),
   (gen_random_uuid(), 'RS', 'Saldanha Marinho'),
   (gen_random_uuid(), 'RS', 'Salto do Jacuí'),
   (gen_random_uuid(), 'RS', 'Salvador das Missões'),
   (gen_random_uuid(), 'RS', 'Salvador do Sul'),
   (gen_random_uuid(), 'RS', 'Sananduva'),
   (gen_random_uuid(), 'RS', 'Santa Bárbara do Sul'),
   (gen_random_uuid(), 'RS', 'Santa Cecília do Sul'),
   (gen_random_uuid(), 'RS', 'Santa Clara do Sul'),
   (gen_random_uuid(), 'RS', 'Santa Cruz do Sul'),
   (gen_random_uuid(), 'RS', 'Santa Margarida do Sul'),
   (gen_random_uuid(), 'RS', 'Santa Maria'),
   (gen_random_uuid(), 'RS', 'Santa Maria do Herval'),
   (gen_random_uuid(), 'RS', 'Santa Rosa'),
   (gen_random_uuid(), 'RS', 'Santa Tereza'),
   (gen_random_uuid(), 'RS', 'Santa Vitória do Palmar'),
   (gen_random_uuid(), 'RS', 'Santana da Boa Vista'),
   (gen_random_uuid(), 'RS', 'Santana do Livramento'),
   (gen_random_uuid(), 'RS', 'Santiago'),
   (gen_random_uuid(), 'RS', 'Santo Ângelo'),
   (gen_random_uuid(), 'RS', 'Santo Antônio da Patrulha'),
   (gen_random_uuid(), 'RS', 'Santo Antônio das Missões'),
   (gen_random_uuid(), 'RS', 'Santo Antônio do Palma'),
   (gen_random_uuid(), 'RS', 'Santo Antônio do Planalto'),
   (gen_random_uuid(), 'RS', 'Santo Augusto'),
   (gen_random_uuid(), 'RS', 'Santo Cristo'),
   (gen_random_uuid(), 'RS', 'Santo Expedito do Sul'),
   (gen_random_uuid(), 'RS', 'São Borja'),
   (gen_random_uuid(), 'RS', 'São Domingos do Sul'),
   (gen_random_uuid(), 'RS', 'São Francisco de Assis'),
   (gen_random_uuid(), 'RS', 'São Francisco de Paula'),
   (gen_random_uuid(), 'RS', 'São Gabriel'),
   (gen_random_uuid(), 'RS', 'São Jerônimo'),
   (gen_random_uuid(), 'RS', 'São João da Urtiga'),
   (gen_random_uuid(), 'RS', 'São João do Polêsine'),
   (gen_random_uuid(), 'RS', 'São Jorge'),
   (gen_random_uuid(), 'RS', 'São José das Missões'),
   (gen_random_uuid(), 'RS', 'São José do Herval'),
   (gen_random_uuid(), 'RS', 'São José do Hortêncio'),
   (gen_random_uuid(), 'RS', 'São José do Inhacorá'),
   (gen_random_uuid(), 'RS', 'São José do Norte'),
   (gen_random_uuid(), 'RS', 'São José do Ouro'),
   (gen_random_uuid(), 'RS', 'São José do Sul'),
   (gen_random_uuid(), 'RS', 'São José dos Ausentes'),
   (gen_random_uuid(), 'RS', 'São Leopoldo'),
   (gen_random_uuid(), 'RS', 'São Lourenço do Sul'),
   (gen_random_uuid(), 'RS', 'São Luiz Gonzaga'),
   (gen_random_uuid(), 'RS', 'São Marcos'),
   (gen_random_uuid(), 'RS', 'São Martinho'),
   (gen_random_uuid(), 'RS', 'São Martinho da Serra'),
   (gen_random_uuid(), 'RS', 'São Miguel das Missões'),
   (gen_random_uuid(), 'RS', 'São Nicolau'),
   (gen_random_uuid(), 'RS', 'São Paulo das Missões'),
   (gen_random_uuid(), 'RS', 'São Pedro da Serra'),
   (gen_random_uuid(), 'RS', 'São Pedro das Missões'),
   (gen_random_uuid(), 'RS', 'São Pedro do Butiá'),
   (gen_random_uuid(), 'RS', 'São Pedro do Sul'),
   (gen_random_uuid(), 'RS', 'São Sebastião do Caí'),
   (gen_random_uuid(), 'RS', 'São Sepé'),
   (gen_random_uuid(), 'RS', 'São Valentim'),
   (gen_random_uuid(), 'RS', 'São Valentim do Sul'),
   (gen_random_uuid(), 'RS', 'São Valério do Sul'),
   (gen_random_uuid(), 'RS', 'São Vendelino'),
   (gen_random_uuid(), 'RS', 'São Vicente do Sul'),
   (gen_random_uuid(), 'RS', 'Sapiranga'),
   (gen_random_uuid(), 'RS', 'Sapucaia do Sul'),
   (gen_random_uuid(), 'RS', 'Sarandi'),
   (gen_random_uuid(), 'RS', 'Seberi'),
   (gen_random_uuid(), 'RS', 'Sede Nova'),
   (gen_random_uuid(), 'RS', 'Segredo'),
   (gen_random_uuid(), 'RS', 'Selbach'),
   (gen_random_uuid(), 'RS', 'Senador Salgado Filho'),
   (gen_random_uuid(), 'RS', 'Sentinela do Sul'),
   (gen_random_uuid(), 'RS', 'Serafina Corrêa'),
   (gen_random_uuid(), 'RS', 'Sério'),
   (gen_random_uuid(), 'RS', 'Sertão'),
   (gen_random_uuid(), 'RS', 'Sertão Santana'),
   (gen_random_uuid(), 'RS', 'Sete de Setembro'),
   (gen_random_uuid(), 'RS', 'Severiano de Almeida'),
   (gen_random_uuid(), 'RS', 'Silveira Martins'),
   (gen_random_uuid(), 'RS', 'Sinimbu'),
   (gen_random_uuid(), 'RS', 'Sobradinho'),
   (gen_random_uuid(), 'RS', 'Soledade'),
   (gen_random_uuid(), 'RS', 'Tabaí'),
   (gen_random_uuid(), 'RS', 'Tapejara'),
   (gen_random_uuid(), 'RS', 'Tapera'),
   (gen_random_uuid(), 'RS', 'Tapes'),
   (gen_random_uuid(), 'RS', 'Taquara'),
   (gen_random_uuid(), 'RS', 'Taquari'),
   (gen_random_uuid(), 'RS', 'Taquaruçu do Sul'),
   (gen_random_uuid(), 'RS', 'Tavares'),
   (gen_random_uuid(), 'RS', 'Tenente Portela'),
   (gen_random_uuid(), 'RS', 'Terra de Areia'),
   (gen_random_uuid(), 'RS', 'Teutônia'),
   (gen_random_uuid(), 'RS', 'Tio Hugo'),
   (gen_random_uuid(), 'RS', 'Tiradentes do Sul'),
   (gen_random_uuid(), 'RS', 'Toropi'),
   (gen_random_uuid(), 'RS', 'Torres'),
   (gen_random_uuid(), 'RS', 'Tramandaí'),
   (gen_random_uuid(), 'RS', 'Travesseiro'),
   (gen_random_uuid(), 'RS', 'Três Arroios'),
   (gen_random_uuid(), 'RS', 'Três Cachoeiras'),
   (gen_random_uuid(), 'RS', 'Três Coroas'),
   (gen_random_uuid(), 'RS', 'Três de Maio'),
   (gen_random_uuid(), 'RS', 'Três Forquilhas'),
   (gen_random_uuid(), 'RS', 'Três Palmeiras'),
   (gen_random_uuid(), 'RS', 'Três Passos'),
   (gen_random_uuid(), 'RS', 'Trindade do Sul'),
   (gen_random_uuid(), 'RS', 'Triunfo'),
   (gen_random_uuid(), 'RS', 'Tucunduva'),
   (gen_random_uuid(), 'RS', 'Tunas'),
   (gen_random_uuid(), 'RS', 'Tupanci do Sul'),
   (gen_random_uuid(), 'RS', 'Tupanciretã'),
   (gen_random_uuid(), 'RS', 'Tupandi'),
   (gen_random_uuid(), 'RS', 'Tuparendi'),
   (gen_random_uuid(), 'RS', 'Turuçu'),
   (gen_random_uuid(), 'RS', 'Ubiretama'),
   (gen_random_uuid(), 'RS', 'União da Serra'),
   (gen_random_uuid(), 'RS', 'Unistalda'),
   (gen_random_uuid(), 'RS', 'Uruguaiana'),
   (gen_random_uuid(), 'RS', 'Vacaria'),
   (gen_random_uuid(), 'RS', 'Vale do Sol'),
   (gen_random_uuid(), 'RS', 'Vale Real'),
   (gen_random_uuid(), 'RS', 'Vale Verde'),
   (gen_random_uuid(), 'RS', 'Vanini'),
   (gen_random_uuid(), 'RS', 'Venâncio Aires'),
   (gen_random_uuid(), 'RS', 'Vera Cruz'),
   (gen_random_uuid(), 'RS', 'Veranópolis'),
   (gen_random_uuid(), 'RS', 'Vespasiano Correa'),
   (gen_random_uuid(), 'RS', 'Viadutos'),
   (gen_random_uuid(), 'RS', 'Viamão'),
   (gen_random_uuid(), 'RS', 'Vicente Dutra'),
   (gen_random_uuid(), 'RS', 'Victor Graeff'),
   (gen_random_uuid(), 'RS', 'Vila Flores'),
   (gen_random_uuid(), 'RS', 'Vila Lângaro'),
   (gen_random_uuid(), 'RS', 'Vila Maria'),
   (gen_random_uuid(), 'RS', 'Vila Nova do Sul'),
   (gen_random_uuid(), 'RS', 'Vista Alegre'),
   (gen_random_uuid(), 'RS', 'Vista Alegre do Prata'),
   (gen_random_uuid(), 'RS', 'Vista Gaúcha'),
   (gen_random_uuid(), 'RS', 'Vitória das Missões'),
   (gen_random_uuid(), 'RS', 'Westfália'),
   (gen_random_uuid(), 'RS', 'Xangri-lá');
