name: Deploy to fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup flyctl
        uses: fly-app/flyctl-github-action@v1
        with:
          version: latest
          api-token: ${{ secrets.FLY_API_TOKEN }}

      - name: Change to project directory
        run: cd api

      - name: Deploy to fly.io
        run: flyctl deploy --config fly.toml
