name: Deploy to fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: cd api
      - run: flyctl deploy --remote-only -a gendaize-scheduler
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
